<?php

namespace Esokia\Bundle\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllQuery($sort){
          $qb = $this->createQueryBuilder('c')
                  ->select('c');
          
           if(!$sort){
            $qb->addOrderBy('c.id', 'DESC');  
            }
            
         return $qb->getQuery();
          
    }
}
