## YAML Template.
---
braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../web/bootstrap
    jquery_path: %kernel.root_dir%/../web/js/jquery-2.1.1.min.js
    less_filter: less 
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig