parameters:
#    esokia_admin.example.class: Esokia\Bundle\AdminBundle\Example

services:
#    esokia_admin.example:
#        class: %esokia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
